export const FIND_BY_CENTRO_COMPLETED = 'pacientes/FIND_BY_CENTRO_COMPLETED';
export const CLEAR_PACIENTE_SEARCH    = 'pacientes/CLEAR_PACIENTE_SEARCH';
export const FIND_PACIENTE_COMPLETED  = 'pacientes/FIND_PACIENTE_COMPLETED';
export const CLEAR_PACIENTE           = 'pacientes/CLEAR_PACIENTE';
export const SAVE_PACIENTE_COMPLETED   = 'pacientes/SAVE_PACIENTE_COMPLETED';
export const DELETE_PACIENTE_COMPLETED = 'pacientes/DELETE_PACIENTE_COMPLETED';
