spring.application.name=lembranza


# Puerto del servidor
server.port=8080

# Configuracion DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/tfgdb
spring.datasource.username=hib
spring.datasource.password=hib123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.mvc.problemdetails.enabled=true

app.jwt.signKey=K3aQz2s7rTf9vB1xY6pLmN4uR8cD0eF2gH5jK8mP1qS4tV7wZ0bC3dE6hJ9L2n5
app.jwt.expirationMinutes=1440


management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true

logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=trace
logging.level.org.springframework.http.converter.json=TRACE
server.error.include-message=always
server.error.include-binding-errors=always
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet.mvc.method.annotation=TRACE
logging.level.org.springframework.web.method.annotation=TRACE